### ISSUE TITLE
docker compose error

### ISSUE THREAD

**Issue by sgort** [ConductionNL/commonground-gateway#1503]
Running `docker compose up --build` fails with the following error

![image](https://github.com/ConductionNL/commonground-gateway/assets/25812095/faaf30bd-f58b-47f5-830c-07fe58601a19)

**Comment by rjzondervan** [comment]
Hi @sgort!

We're working on it. We'll keep you posted.

**Comment by rjzondervan** [comment]
Hi @sgort,

We just merged the PR above, could you check if running docker compose up with a new pull returns better results?

**Comment by sgort** [comment]
Guess it's working now.

![image](https://github.com/ConductionNL/commonground-gateway/assets/25812095/f608c585-c864-4ff2-b792-d5012fdea598)

**Comment by sgort** [comment]
Next question... Hoe/waar kom ik **in de Common Gateway**?

"Omdat OpenCatalogi een Common Gateway plugin is kan je vervolgens simpelweg in de Common Gatewayy naar plugins navigeren, zoeken naar OpenCatalogi, en op installeren klikken." Bron: https://github.com/OpenCatalogi#alternatieve-installatie-route

**Comment by sgort** [comment]
Die mag in de doc erbij. Ik zal een PR voorbereiden 
![image](https://github.com/ConductionNL/commonground-gateway/assets/25812095/7bf73e7e-4094-4061-a476-5c8498fc487a)

**Comment by sgort** [comment]
Guess common-gateway/changeme! aren't the right login credentials?

**Comment by WilcoLouwerse** [comment]
Hi @sgort,

The default credentials for the common gateway are:
no-reply@test.com
!ChangeMe!

I hope this helps! Where and how did you find the common-gateway/changeme! credentials?

**Comment by sgort** [comment]
See network error
![image](https://github.com/ConductionNL/commonground-gateway/assets/25812095/c3f1b207-7e0d-4d8e-96f6-2e4eb5b95aab)

**Comment by sgort** [comment]
Found credentials here
https://github.com/sgort/commonground-gateway/blob/c8aa0649d0f2c6b217825ec68f5fd7dad2cab3e5/.env#L166

**Comment by rjzondervan** [comment]
Has the PHP container shown the following lines yet?
```
commonground-gateway-php-1       | [21-Jun-2023 08:18:31] NOTICE: fpm is running, pid 1
commonground-gateway-php-1       | [21-Jun-2023 08:18:31] NOTICE: ready to handle connections
```

**Comment by WilcoLouwerse** [comment]
(If not^ the common gateway control panel can't reach the common gateway yet)

**Comment by sgort** [comment]
Guess not
![image](https://github.com/ConductionNL/commonground-gateway/assets/25812095/c5f10b4c-8199-459b-8d55-c9fbd794711e)

**Comment by rjzondervan** [comment]
Ah, seems your gateway hasn't got permission to create its dependency folder yet. Could you create the folder vendor in the api folder and try again?

**Comment by rjzondervan** [comment]
Okay, I see you use Ubuntu, in that case it might be wise to run the following commands:
```
chmod 777 -R api/vendor api/public api/var api/config
chmod 777 api/composer.lock api/composer.json api/src/Logger/SessionDataProcessor.php
```
Docker and ubuntu manage to create some permission collisions on the gateway unfortunately.

**Comment by sgort** [comment]
Nice!

![image](https://github.com/ConductionNL/commonground-gateway/assets/25812095/ffa8a3be-d05b-447b-b54c-4f2c0f921691)
